name: Claude Documentation Sync

on:
  pull_request:
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.svelte'
      - 'src/lib/types/**'
      - 'src/lib/services/**'
      - 'supabase/migrations/**'
    types: [opened, synchronize]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Update Documentation with Claude
        uses: anthropics/claude-code-action@beta
        with:
          direct_prompt: |
            I notice this PR contains changes to TypeScript/Svelte files or database migrations.
            Please review the changes and update any relevant documentation:
            
            1. **CLAUDE.md** - Update if new patterns, tools, or architectural decisions are introduced
            2. **docs/ARCHITECTURE.md** - Update for structural changes
            3. **docs/SUPABASE_INTEGRATION.md** - Update for database schema changes
            4. **README.md** - Update if new features or setup steps are added
            5. **Component documentation** - Add/update JSDoc comments in components
            
            Key areas to check:
            - New database tables or schema changes
            - New API endpoints or services
            - New components or major component changes
            - Changes to authentication flow
            - New dependencies or setup requirements
            - Updates to development commands or workflows
            
            Only make documentation updates that are directly related to the code changes.
            Commit any documentation updates to this PR branch.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowed_tools: "Bash(git diff --name-only HEAD~1),Bash(git diff HEAD~1),View,Edit,Write,GlobTool,GrepTool"
          timeout_minutes: 20