name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          trigger_phrase: "@claude"
          assignee_trigger: "claude"
          timeout_minutes: 30
          allowed_tools: "Bash(pnpm install --frozen-lockfile),Bash(pnpm build),Bash(pnpm test),Bash(pnpm lint),Bash(pnpm check),Edit,Write,View,GlobTool,GrepTool"
          custom_instructions: |
            You are working on a SvelteKit 5 TypeScript application with Supabase backend.
            Always follow the project's CLAUDE.md guidelines and existing code patterns.
            Run pnpm commands instead of npm. Follow Svelte 5 runes syntax.
            Always run lint and type checking after making code changes.