name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  automated-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest


      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            Please review this pull request thoroughly. Focus on:
            
            1. **Code Quality**: Check for adherence to TypeScript/SvelteKit best practices
            2. **Svelte 5 Compliance**: Ensure proper use of runes ($state, $derived, $effect)
            3. **Security**: Look for potential security issues, especially around Supabase auth
            4. **Performance**: Identify performance bottlenecks or inefficient patterns
            5. **Testing**: Suggest areas that need test coverage
            6. **Documentation**: Check if changes need documentation updates
            7. **Accessibility**: Ensure UI components are accessible
            8. **Type Safety**: Verify proper TypeScript usage
            
            Check the CLAUDE.md file for project-specific guidelines.
            Provide specific, actionable feedback with code examples where helpful.
            If changes look good, acknowledge what was done well.
          allowed_tools: "Bash(git diff --name-only HEAD~1),Bash(git diff HEAD~1),Bash(pnpm lint),Bash(pnpm check),View,GlobTool,GrepTool"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: 15

      - name: Post Review Comment
        if: steps.code-review.outputs.conclusion == 'success'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const executionFile = '${{ steps.code-review.outputs.execution_file }}';
            const executionLog = JSON.parse(fs.readFileSync(executionFile, 'utf8'));
            
            // Extract the review content from the execution log
            let review = '';
            for (let i = executionLog.length - 1; i >= 0; i--) {
              if (executionLog[i].role === 'assistant') {
                review = executionLog[i].content;
                break;
              }
            }
            
            if (review) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🤖 Claude Code Review\n\n${review}\n\n---\n*Generated by Claude Code Assistant*`
              });
            }