name: Qodana with Code Coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - testing
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests with coverage for Qodana
        run: pnpm test:coverage:qodana
        continue-on-error: true

      - name: Create empty coverage file if missing
        run: |
          if [ ! -f ".qodana/code-coverage/lcov.info" ]; then
            echo "No coverage data found. Creating empty lcov.info to prevent errors."
            mkdir -p .qodana/code-coverage
            touch .qodana/code-coverage/lcov.info
          fi

      - name: Check coverage file before Qodana
        run: |
          echo "Checking coverage file:"
          if [ -f ".qodana/code-coverage/lcov.info" ]; then
            echo "Coverage file exists. Size:"
            ls -la .qodana/code-coverage/lcov.info
            echo "First 10 lines of the file:"
            head -n 10 .qodana/code-coverage/lcov.info || echo "Empty file"
          else
            echo "Coverage file does not exist."
          fi

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        continue-on-error: true
        env:
          QODANA_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoidjVEOW4iLCJvcmdhbml6YXRpb24iOiJ4UFE0ciIsInRva2VuIjoiTXJOWW8ifQ.2vBF9KEG3y2LH9KQD36DGtzLfyougQJ4Cat1p3Vsduk"
        with:
          args: "--coverage-dir,.qodana/code-coverage --no-symlinks"

      - name: Check Qodana logs
        if: ${{ always() }}
        run: |
          echo "Checking Qodana logs:"
          if [ -d "/home/runner/work/_temp/qodana/results/logs" ]; then
            ls -la /home/runner/work/_temp/qodana/results/logs
            echo "Content of log files:"
            for file in /home/runner/work/_temp/qodana/results/logs/*; do
              echo "=== $file ==="
              cat "$file" || echo "Failed to read file"
              echo "=============="
            done
          else
            echo "Qodana logs directory not found."
          fi

