name: Qodana with Code Coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - testing
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests with coverage
        run: pnpm test:coverage
        continue-on-error: true

      - name: Prepare coverage data for Qodana
        run: |
          mkdir -p .qodana/code-coverage
          if [ -f "coverage/lcov.info" ]; then
            cp coverage/lcov.info .qodana/code-coverage/
            echo "Coverage data copied to .qodana/code-coverage/"
          else
            echo "No coverage data found. Creating empty file."
            touch .qodana/code-coverage/lcov.info
          fi

      - name: Qodana Scan
        uses: JetBrains/qodana-action@latest
        continue-on-error: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "--coverage-dir,.qodana/code-coverage"

