name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: '10.3.0'

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test
      
    - name: Copy coverage to Qodana directory
      run: |
        mkdir -p .qodana/code-coverage
        cp -r coverage/* .qodana/code-coverage/
      
    - name: Archive coverage data
      uses: actions/upload-artifact@v4
      with:
        name: coverage-data
        path: .qodana/code-coverage

    - name: Qodana Scan
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_2144836382 }}
      with:
        args: "--apply-fixes"
        pr-mode: false